### ISSUE TITLE
File List of Uploaded Documents to NC not being updated automtically

### ISSUE THREAD

**Issue by chechani** [pibico/pibiDAV#11]
File List of Uploaded Documents to NC is not being updated automatically. Seen this in the addon there is a button to refresh the file list , so it is being refreshed on click. However in relevant doc it is not being refreshed as below image

![image](https://user-images.githubusercontent.com/6291292/186090801-0f07d899-79de-409f-b8ba-3f5d533ff2e3.png)

**Comment by pibico** [comment]
File list in current branch revision is only accessible on addon and button must be clicked to update list. If Files List is present in other doctypes this is a remaining of other previous installation, and this is not correct. You should do bench migrate.

**Comment by chechani** [comment]
Thanks  ! should we not it automatically update the file list once we go to that record? Yes, I understand AddON so need to remove fields that still exists
