### ISSUE TITLE
Feature Request-Store Files Directly to NC from URL link

### ISSUE THREAD

**Issue by chechani** [pibico/pibiDAV#13]
We received Xray through Whatsapp and we want to save the x-ray to the relevant patient folder in NC so can you accommodate to consider saving files to NC directly from URL ( WhatsApp images link, in my case) and create a record NC record for attachment AS LINK AND UPLOADED TO NC BOTH

**Comment by pibico** [comment]
For this we need to include in file nextcloud.py and in client class a new method for putting url and no files. As a workaround you could create a text file and inside it place the url link and upload the text file as a normal file

**Comment by chechani** [comment]
Thanks,  As Whatsapp URL expires after some time so xray needed bo be stored on our server
