### ISSUE TITLE
Why Abbreviation is must to create folder

### ISSUE THREAD

**Issue by chechani** [pibico/pibiDAV#14]
Why Abbreviation is must to create folder, as we want to create folder directly like in the name of customer or so on

![image](https://user-images.githubusercontent.com/6291292/186103560-fa13d343-ec39-49dc-b8db-459ff72fa3b6.png)

**Comment by pibico** [comment]
> Why Abbreviation is must to create folder, as we want to create folder directly like in the name of customer or so on
> 
> ![image](https://user-images.githubusercontent.com/6291292/186103560-fa13d343-ec39-49dc-b8db-459ff72fa3b6.png)

Abbreviation is needed in the way the folders are named. Folder Root Name in NC is taken from Folder Tree Doctype -Folder Name, but children in the folder set are renamed taking the abbrevation followed by -. As a workaround if no children are in the referred Folder Set, you can split the Folder Name in two sections, one for abbreviation and the other for the rest of the name.

We mean if want to create folders in NC for customer "Bank of America", we could place on Abbreviation "Bank" ando on Folder Name "of America"
