### ISSUE TITLE
Create a folder automatically on creation of record of certain doc types

### ISSUE THREAD

**Issue by chechani** [pibico/pibiDAV#3]
Feature Request
=============

Facility to create a folder automatically on creation of certain doc types like Customer, Supplier, Patient, Student etc (based on setting defined for every doctype). Get user path and sharable path with configurable sharing type. The folder path for internal users and stakeholders should be derived from NC. This will help to upload files to NC directly by internal users and access given by stakeholders so they can upload or download. Users will get this newly created blank folder in the windows client, and they will put files locally.

**Comment by pibico** [comment]
Let me understand the requirement transforming it in actions, i.e. for a new Customer:
1. Create a Customer normally
2. After creating the Customer, there would be a custom button, let's name it `Create NC Folders` that on click should create the new Folder Set in NextCloud. For that purpose we would need.

- On `NextCloud Settings` `Reference Item` Child Table we should have a new column on each `Reference DocType` telling which `Folder Set` Template to Recreate on the NextCloud Instance
- On `Folder Set` there would be a new DocField `Default NC Folder` where to place the complete NextCloud path parent for the new Customer Folder
- With these two previous items given, `Folder Set` Template and NextCloud Parent Path, we should automatically recreate the `Folder Set` in NextCloud.
- At this point, we would pop up a new frappe Dialog, for asking the user to give inputs for naming the new Folder in NextCloud, or we could give the name of the Root Folder automatically from the DocType name recently created. Which would be the requirement here, and which inputs to be given, i.e. the sharing type? After those inputs we could submit and create the Folders in the NextCloud Instance.

If these steps are ok and you confirm, then we could make the programming.

**Comment by chechani** [comment]
Thanks for listing out requirement in detail , our following explanation should clear the objective
Let me understand the requirement transforming it in actions, i.e. for a new Customer:
1.	Create a Customer normally-**ok**
2.	After creating the Customer, there would be a custom button, let's name it Create NC Folders that on click should create the new Folder Set in NextCloud. For that purpose we would need.
**Explanation**
Instead of a button, we should give a check box “ **Create NC Folder “** field like “NC Enable” so through a server script after creating – Create NC Folder function should be called. The value of the check box will be prefilled based on the default setting and can be changed based on the requirement to create NC Folder for that customer or not.

Additionally, Your idea of a button is very good. but when we are creating a new Customer / Patient, the button will not be much as we want to automatically notify customers about his shared folder to upload their documents in NC folder. Through the Internal link , users will have access to this folder if they have access to that particular customer record.

•	On NextCloud Settings Reference Item Child Table we should have a new column on each Reference DocType telling which Folder Set Template to Recreate on the NextCloud Instance.
**Explanation**
In the child Table, we should give parameters for automated naming of the folder as defined for that doctype like someone wants to create a folder on a Patient ID or Patient Mobile ( Combination of tags ) as you already assigned tag automatically . 

the facility of password oriented shared NC folder should be there and we can define in setting what will be the default password and this should be saved back in that record as while communicating to customer , we can notify the password of the shared folder.

•	On Folder Set there would be a new DocField Default NC Folder where to place the complete NextCloud path parent for the new Customer Folder

**Explanation**
It should be saved automatically default NC folder setting done for that Document type- Which you already asking. so the idea is that a particular patient folder is created under patient doctype or any other folder defined for that 

•	With these two previous items given, Folder Set Template and NextCloud Parent Path, we should automatically recreate the Folder Set in NextCloud.

**It is clear from above** 

•	At this point, we would pop up a new frappe Dialog, for asking the user to give inputs for naming the new Folder in NextCloud, or we could give the name of the Root Folder automatically from the DocType name recently created. Which would be the requirement here, and which inputs to be given, i.e. the sharing type? After those inputs we could submit and create the Folders in the NextCloud Instance.
**It should be based on setting as explained and no pop ups should be given.** 

We should get internal user path for that folder so user can upload documents in nwly created NC folder directly and Shared path ( Different permission option of NC should be configurable for each doc type and picked as link in that document to be amended .

**The objective is to share a NC folder through any communication media , like for professional firms , client will upload docs , patient will upload their medical records etc**


If these steps are ok and you confirm, then we could make the programming.

**Comment by pibico** [comment]
Some questions arise from explanations. 
1. Folders to be created automatically in NextCloud would be only one folder or a Folder Set with children folders?
2. Documents uploaded directly to NextCloud should be synchronized in Frappe/ERPNext? This functionality wasn't originally considered for pibiDAV. Only uploading documents from Frappe to NextCloud was considered. We considered the use for example for Companies with Construction Projects (EPCs) where a control of deliverables is needed. On that case, the deliverables to control are uploaded to Frappe and derived automatically to NextCloud.
3. Getting the fileid for internal path and shared link for the folder is not a problem (nextcloud.py script has all this functions), so this urls can be given after creating the folders. The shared Nextcloud links would be just public links with password or with more restrictions as NextCloud allows?

**Comment by pibico** [comment]
It has been implemented the new Feature and done on Customer as an example for other Core Doctypes such as Patient. What it does not run is de assignation of password on the script. If I run the nextcloud api on console it assigns password on the share link, but in the after_insert event script, the password is not assigned (this is a bug that I will investigate).

First of all, on NextCloud Settings, new columns are added. In those columns we fill the docfields we should use for abbreviation and Title of the NC Folder to create. Also a Folder Set must be created and after linked in the settings.

Let's see the example in pictures. First the NextCloud Settings
![imagen](https://user-images.githubusercontent.com/69711454/166159831-895c3066-3991-461e-af56-b70fa8963369.png)
Second the Folder Set Template for Customer. The 3 digits for CLI in the template are substituted by the abbreviation on folder creation
![imagen](https://user-images.githubusercontent.com/69711454/166159865-a09dc73f-1af6-439a-9470-851f8447785d.png)
Once created the customer, the links and path are filled in doctype
![imagen](https://user-images.githubusercontent.com/69711454/166159917-e39510f4-8f7c-4fc5-87c7-3122bff8ef31.png)
In NextCloud Folders have been generated.
![imagen](https://user-images.githubusercontent.com/69711454/166159939-e6ec257e-552f-4c9b-b896-37eeaa4880a1.png)

**Comment by chechani** [comment]
Thanks a lot, we will review and give feedback. On quick review of your note, we understand you are given the flexibility to decide folder name, folder path in NC and predefined folder set required for that doctype. Password and choosing sharing options like upload/download or download only or read only is very important in the business scenario. I will update my previous installation. In the meantime, we request to identify the bugs you mentioned and ensure the things I mentioned are also incorporated. We have a Hospital Chain Client and will introduce them to deploy asap to get feedback at customer end. Thanks again

**Comment by pibico** [comment]
For sharing options i will add a new column on settings with a select with the different options. Apart from the bug on using the Nextcloud API with the password, for the sharing link to run I always make a default sharing (read only) and then modify the sharing with other options (actually I am placing always read, write, delete). That's because if I make the sharing with the options selected on  creation, it does not make any effect.
