### ISSUE TITLE
TypeError: must be str, not dict

### ISSUE THREAD

**Issue by chechani** [pibico/pibiDAV#4]
After updating, getting the following error on creating a new customer and enabling Create NC Folder and NC Enable, Additionally,  NC Folder Share Link and NC Folder Internal Link should be visible and read-only so once less confusion for non-tech savvy user, request to add columns art right places to set folder set or other documents etc so things on do

![image](https://user-images.githubusercontent.com/6291292/166225939-1878db9c-c55c-4d89-b884-23ced42496f2.png)

### App Versions
```
{
	"erpnext": "13.25.1",
	"erpnext_telegram_integration": "1.0.1",
	"frappe": "13.25.0",
	"frappe_system_monitor": "0.0.1",
	"pibicut": "0.0.1",
	"pibidav": "0.0.1",
	"professional": "0.0.1",
	"whitelabel": "0.0.1",
	"whitetheme_v13": "0.0.1"
}
```
### Route
```
Form/Customer/new-customer-2
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 287, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 309, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 261, in insert
    self.run_method("after_insert")
  File "apps/frappe/frappe/model/document.py", line 873, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1165, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1150, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/pibidav/pibidav/pibidav/custom.py", line 40, in create_nc_folder
    root_path = path + abbreviation + " " + strmain + "/"
TypeError: must be str, not dict

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 68, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1213, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 287, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 309, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 261, in insert
    self.run_method("after_insert")
  File "apps/frappe/frappe/model/document.py", line 873, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1165, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1150, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/pibidav/pibidav/pibidav/custom.py", line 40, in create_nc_folder
    root_path = path + abbreviation + " " + strmain + "/"
TypeError: must be str, not dict

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Customer\",\"name\":\"new-customer-1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"naming_series\":\"CUST-.YYYY.-\",\"customer_type\":\"Company\",\"gst_category\":\"Unregistered\",\"export_type\":\"\",\"create_nc_folder\":1,\"nc_enable\":1,\"so_required\":0,\"dn_required\":0,\"disabled\":0,\"is_internal_customer\":0,\"language\":\"en\",\"is_frozen\":0,\"customer_group\":\"All Customer Groups\",\"territory\":\"All Territories\",\"nc_folder\":\"/ERPNext/Customer/\",\"customer_name\":\"my folder set test\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery22400429981756072260751": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 1586,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "TypeError: must be str, not dict"
}
```

**Comment by pibico** [comment]
> After updating, getting the following error on creating a new customer and enabling Create NC Folder and NC Enable
> 
> ![image](https://user-images.githubusercontent.com/6291292/166225939-1878db9c-c55c-4d89-b884-23ced42496f2.png)
> ### App Versions
> 
> ```
> {
> 	"erpnext": "13.25.1",
> 	"erpnext_telegram_integration": "1.0.1",
> 	"frappe": "13.25.0",
> 	"frappe_system_monitor": "0.0.1",
> 	"pibicut": "0.0.1",
> 	"pibidav": "0.0.1",
> 	"professional": "0.0.1",
> 	"whitelabel": "0.0.1",
> 	"whitetheme_v13": "0.0.1"
> }
> ```
> 
> ### Route
> 
> ```
> Form/Customer/new-customer-2
> ```
> 
> ### Trackeback
> 
> ```
> Traceback (most recent call last):
>   File "apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
>     doc.save()
>   File "apps/frappe/frappe/model/document.py", line 287, in save
>     return self._save(*args, **kwargs)
>   File "apps/frappe/frappe/model/document.py", line 309, in _save
>     return self.insert()
>   File "apps/frappe/frappe/model/document.py", line 261, in insert
>     self.run_method("after_insert")
>   File "apps/frappe/frappe/model/document.py", line 873, in run_method
>     out = Document.hook(fn)(self, *args, **kwargs)
>   File "apps/frappe/frappe/model/document.py", line 1165, in composer
>     return composed(self, method, *args, **kwargs)
>   File "apps/frappe/frappe/model/document.py", line 1150, in runner
>     add_to_return_value(self, f(self, method, *args, **kwargs))
>   File "apps/pibidav/pibidav/pibidav/custom.py", line 40, in create_nc_folder
>     root_path = path + abbreviation + " " + strmain + "/"
> TypeError: must be str, not dict
> 
> Traceback (most recent call last):
>   File "apps/frappe/frappe/app.py", line 68, in application
>     response = frappe.api.handle()
>   File "apps/frappe/frappe/api.py", line 55, in handle
>     return frappe.handler.handle()
>   File "apps/frappe/frappe/handler.py", line 31, in handle
>     data = execute_cmd(cmd)
>   File "apps/frappe/frappe/handler.py", line 68, in execute_cmd
>     return frappe.call(method, **frappe.form_dict)
>   File "apps/frappe/frappe/__init__.py", line 1213, in call
>     return fn(*args, **newargs)
>   File "apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
>     doc.save()
>   File "apps/frappe/frappe/model/document.py", line 287, in save
>     return self._save(*args, **kwargs)
>   File "apps/frappe/frappe/model/document.py", line 309, in _save
>     return self.insert()
>   File "apps/frappe/frappe/model/document.py", line 261, in insert
>     self.run_method("after_insert")
>   File "apps/frappe/frappe/model/document.py", line 873, in run_method
>     out = Document.hook(fn)(self, *args, **kwargs)
>   File "apps/frappe/frappe/model/document.py", line 1165, in composer
>     return composed(self, method, *args, **kwargs)
>   File "apps/frappe/frappe/model/document.py", line 1150, in runner
>     add_to_return_value(self, f(self, method, *args, **kwargs))
>   File "apps/pibidav/pibidav/pibidav/custom.py", line 40, in create_nc_folder
>     root_path = path + abbreviation + " " + strmain + "/"
> TypeError: must be str, not dict
> ```
> 
> ### Request Data
> 
> ```
> {
> 	"type": "POST",
> 	"args": {
> 		"doc": "{\"docstatus\":0,\"doctype\":\"Customer\",\"name\":\"new-customer-1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"naming_series\":\"CUST-.YYYY.-\",\"customer_type\":\"Company\",\"gst_category\":\"Unregistered\",\"export_type\":\"\",\"create_nc_folder\":1,\"nc_enable\":1,\"so_required\":0,\"dn_required\":0,\"disabled\":0,\"is_internal_customer\":0,\"language\":\"en\",\"is_frozen\":0,\"customer_group\":\"All Customer Groups\",\"territory\":\"All Territories\",\"nc_folder\":\"/ERPNext/Customer/\",\"customer_name\":\"my folder set test\"}",
> 		"action": "Save"
> 	},
> 	"btn": {
> 		"jQuery22400429981756072260751": {
> 			"events": {
> 				"click": [
> 					{
> 						"type": "click",
> 						"origType": "click",
> 						"guid": 1586,
> 						"namespace": ""
> 					}
> 				]
> 			}
> 		}
> 	},
> 	"freeze": true,
> 	"headers": {},
> 	"error_handlers": {},
> 	"url": "/api/method/frappe.desk.form.save.savedocs"
> }
> ```
> 
> ### Response Data
> 
> ```
> {
> 	"exception": "TypeError: must be str, not dict"
> }
> ```

Please provide me the NextCloud Settings for Customer DocType please

**Comment by pibico** [comment]
abbreviation from NextCloud Settings must be an existing DocField from Customer DocType, also folder_name must be another existing DocField from Customer DocType. No free text is admitted

**Comment by pibico** [comment]
Additionally, NC Folder Share Link and NC Folder Internal Link should be visible and read-only so once less confusion for non-tech savvy user, request to add columns art right places to set folder set or other documents etc so things on do

NC Folder Share Link and NC Folder Internal Link are docfields of type 'Read Only' already used to fill with an '<a href="">link</a>' value for folders whenever created the folders in NC.

The new column you mean is something like in the picture?

![imagen](https://user-images.githubusercontent.com/69711454/166229257-90d3dae1-f440-4aeb-bb38-d1b3405e4c36.png)

**Comment by chechani** [comment]
> abbreviation from NextCloud Settings must be an existing DocField from Customer DocType, also folder_name must be another existing DocField from Customer DocType. No free text is admitted. Abbreviation and Folder Name for the NC Folder are derived so from existing DocFields in Customer DocType.
> 
> ![imagen](https://user-images.githubusercontent.com/69711454/166226960-41e5f1d0-755d-49a7-b7b4-e09f04e805a9.png)

please use columns in this doctype please

**Comment by chechani** [comment]
I am struggling to understand this new feature, Now get the following error


### App Versions
```
{
	"erpnext": "13.25.1",
	"erpnext_telegram_integration": "1.0.1",
	"frappe": "13.25.0",
	"frappe_system_monitor": "0.0.1",
	"pibicut": "0.0.1",
	"pibidav": "0.0.1",
	"professional": "0.0.1",
	"whitelabel": "0.0.1",
	"whitetheme_v13": "0.0.1"
}
```
### Route
```
Form/Customer/new-customer-1
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 287, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 309, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 261, in insert
    self.run_method("after_insert")
  File "apps/frappe/frappe/model/document.py", line 873, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1165, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1150, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/pibidav/pibidav/pibidav/custom.py", line 40, in create_nc_folder
    root_path = path + abbreviation + " " + strmain + "/"
TypeError: must be str, not dict

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 68, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1213, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 287, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 309, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 261, in insert
    self.run_method("after_insert")
  File "apps/frappe/frappe/model/document.py", line 873, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1165, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1150, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/pibidav/pibidav/pibidav/custom.py", line 40, in create_nc_folder
    root_path = path + abbreviation + " " + strmain + "/"
TypeError: must be str, not dict

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Customer\",\"name\":\"new-customer-1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"naming_series\":\"CUST-.YYYY.-\",\"customer_type\":\"Company\",\"gst_category\":\"Unregistered\",\"export_type\":\"\",\"so_required\":0,\"dn_required\":0,\"disabled\":0,\"is_internal_customer\":0,\"nc_enable\":1,\"language\":\"en\",\"is_frozen\":0,\"create_nc_folder\":1,\"customer_group\":\"All Customer Groups\",\"territory\":\"All Territories\",\"nc_folder\":\"/ERPNext/Customer/\",\"customer_name\":\"My Test One\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery224099297714997689261": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 946,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "TypeError: must be str, not dict"
}
```

**Comment by chechani** [comment]
Following the setting explained in your example for customer to understand, but still missing to see it in action

![image](https://user-images.githubusercontent.com/6291292/166246177-90a1810a-e7f6-4ab4-a316-735a2286456e.png)


### App Versions
```
{
	"erpnext": "13.25.1",
	"erpnext_telegram_integration": "1.0.1",
	"frappe": "13.25.0",
	"frappe_system_monitor": "0.0.1",
	"pibicut": "0.0.1",
	"pibidav": "0.0.1",
	"professional": "0.0.1",
	"whitelabel": "0.0.1",
	"whitetheme_v13": "0.0.1"
}
```
### Route
```
Form/Customer/new-customer-1
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 287, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 309, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 261, in insert
    self.run_method("after_insert")
  File "apps/frappe/frappe/model/document.py", line 873, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1165, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1150, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/pibidav/pibidav/pibidav/custom.py", line 43, in create_nc_folder
    create_nc_dirs(node_name, path, abbreviation, strmain, digits)
  File "apps/pibidav/pibidav/pibidav/custom.py", line 515, in create_nc_dirs
    folder = nclient.mkdir(root_path)
  File "apps/pibidav/pibidav/pibidav/nextcloud.py", line 853, in mkdir
    return self._make_dav_request('MKCOL', path)
  File "apps/pibidav/pibidav/pibidav/nextcloud.py", line 1968, in _make_dav_request
    raise HTTPResponseError(res)
pibidav.pibidav.nextcloud.HTTPResponseError: HTTP error: 409

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 68, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1213, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 287, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 309, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 261, in insert
    self.run_method("after_insert")
  File "apps/frappe/frappe/model/document.py", line 873, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1165, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1150, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/pibidav/pibidav/pibidav/custom.py", line 43, in create_nc_folder
    create_nc_dirs(node_name, path, abbreviation, strmain, digits)
  File "apps/pibidav/pibidav/pibidav/custom.py", line 515, in create_nc_dirs
    folder = nclient.mkdir(root_path)
  File "apps/pibidav/pibidav/pibidav/nextcloud.py", line 853, in mkdir
    return self._make_dav_request('MKCOL', path)
  File "apps/pibidav/pibidav/pibidav/nextcloud.py", line 1968, in _make_dav_request
    raise HTTPResponseError(res)
pibidav.pibidav.nextcloud.HTTPResponseError: HTTP error: 409

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Customer\",\"name\":\"new-customer-1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"naming_series\":\"CUST-.YYYY.-\",\"customer_type\":\"Company\",\"gst_category\":\"Unregistered\",\"export_type\":\"\",\"so_required\":0,\"dn_required\":0,\"disabled\":0,\"is_internal_customer\":0,\"nc_enable\":1,\"language\":\"en\",\"is_frozen\":0,\"create_nc_folder\":1,\"represents_company\":\"\",\"nc_folder\":\"/ERPNext/Customer/\",\"customer_name\":\"my Company\",\"customer_group\":\"Commercial\",\"territory\":\"India\",\"tax_id\":\"ty789uy\",\"tax_category\":\"\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery2240188933096459264151": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 572,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "pibidav.pibidav.nextcloud.HTTPResponseError: HTTP error: 409"
}
```

**Comment by chechani** [comment]
Thanks , Got created a folder, I have to change the default folder path selected for backup in nextcloud setting. So it is necessary to choose the default folder setting for backup. Backup should not be mixed with auto folder creation. I could not understand what is the use of folder set in auto folder creation functionally. I also removed tax_id, I will explore it now.

**Comment by chechani** [comment]
What is the logic behind making abbreviations is a must, otherwise it throws the error.
why were two folders created with chosen abbreviation under created folder name, what is logic behind it

![Uploading image.png…]()

**Comment by pibico** [comment]
What is the logic behind making abbreviations is a must, otherwise it throws the error.
why were two folders created with chosen abbreviation under created folder name, what is the logic behind it. I think you creating read-only (downloadable ) folders only, no effect of security type and password 

We have considered always a Folder Set Template to be used for creating the folders. We have considered that Folder Set has or not children. Let's make the example for a Customer Folder Set.
Folder Set:
(CLI) Customer Template .... this is the root folder in the Folder Set
  CLI C-First Children ............ this is one of the children in the Folder Set with 3 digits and then the Name.

Root Folder named **(CLI) Customer Template**, will be substituted at the creation of the folders in NC by the abbreviation + folder_name. Abbreviation cannot be empty, but can be one (1) space character, and folder_name is the name of the new Folder.

In case there are children folders the abbreviation will substitute always the first 3 digits, so the children would be named in Folder Set with some kind of first text (3 digits) and then the title. That's because on a Frappe Tree, the nodes cannot have the same name and that's a way of achieving it.

The logic of the children folders having the abbreviation is due to sharing in NextCloud folders below a root. If the folders are shared without a reference of their root, perhaps all the children folders from different roots are named the same.
 
And finally, in the new version I have just uploaded to GitHub, the password is working now. One important subject about the password is that must be following the directives present in NextCloud. So not normal passwords are allowed.
