### ISSUE TITLE
Sharing Options and Password should be part of Transaction and Not Setting

### ISSUE THREAD

**Issue by chechani** [pibico/pibiDAV#5]
### Suggestions for Feature Incorporated

**Thanks, Sharing Option and Password is working.** 

However, both options should be part of the transaction and not Nextcloud Setting for a Doctype. You will be agreed with us, on how we can set similar passwords for all customers.  

These options should be visible below the field **Password should be the choice if filled "Create NC Folder"** on selecting this option. 

Password character or length condition should be mentioned in the description of the password field. 

Password setting should be chosen and if it remains blank, then no password should be set and only a sharable link should be generated and filled.

All these options should be put in the first section **below the NC Enable field** for a better visibility

**Comment by pibico** [comment]
Feature is incorporated in the new uploaded version, removed password and sharing options from NextCloud Settings and placed on Custom Fields for the Core Doctype (in this case Customer). Function on server changed to accomodate these changes. Password and Sharing Option Fields are settled to read_only once doctype is created and inserted.

**Comment by chechani** [comment]
Great, It worked perfectly for Customer Doctype, By accident, there was a trailing space so it could not be synched with Nextcloud Windows Clent. We request to remove trailing space wherever possible to avoid such tinny issues

![image](https://user-images.githubusercontent.com/6291292/166444934-af184d7b-835c-4e26-8fe8-b88d94050d46.png)
