### ISSUE TITLE
Feature Request - Project Document Templates to Project -Suggestion to Copy Folder and/or Files only

### ISSUE THREAD

**Issue by chechani** [pibico/pibiDAV#7]
**### This enhances the usability of this APP by most professional services organizations**

ERPNext has Project Template features that are very good to create new Projects where we got a list of tasks also copied from Project Templates. If we can enhance this feature by copy commands where we can copy documents from the Template folder or a single file (where a single doc may require many places). We envisage that the copied folder and files can be chosen by using NC Browser (as out of 10 we may need 6 only and so on) and then inserted into a custom Document designed like Project Documents with a link field to the project. Thus, we will have a listing of project documents in the dashboard and can jump to a list of documents for that project like we can jump for Task.

This feature can be incorporated with the integration of NC as NC documents will be available offline through the NC windows client.

We believe you can plan and structure this feature with ease and with the best UI.
This feature is a great value addition for businesses and professionals who need to create a set of documents based on templates and repetitive tasks for them.

We can give the flexibility to plan this functionally for any doctype for the ned of a copy of documents 

**You should be well aware of this functionality and can refer ERPNext again in this context.**

Adding a few screenshots just for reference 

![1templates](https://user-images.githubusercontent.com/6291292/166450021-a94a4cff-61df-422e-9f56-6ccc69e84493.jpg)
![Project Documents -Details](https://user-images.githubusercontent.com/6291292/166450239-928f9461-2d94-4b9f-b64f-6555848af5f7.jpg)
![Project Documents](https://user-images.githubusercontent.com/6291292/166450252-1d302359-779f-4c6c-b782-f892f3204a0e.jpg)
![Project Documnets Link](https://user-images.githubusercontent.com/6291292/166450265-2e033657-ae24-46fd-b320-3debe362493d.jpg)
![project](https://user-images.githubusercontent.com/6291292/166450270-ecc97dcb-03fa-43f8-85ee-9340afb8f380.jpg)
![template selection dialog](https://user-images.githubusercontent.com/6291292/166450282-1e007784-9ce4-4742-9746-9895d40b0daa.jpg)
![template selection](https://user-images.githubusercontent.com/6291292/166450293-a10c09a2-5748-4a24-a814-4031d0b152e1.jpg)

**Comment by pibico** [comment]
We'll study

**Comment by chechani** [comment]
We are actively seeing this so suggested this, Based on good features already incorporated like **"This child table is filled automatically with all documents uploaded also to NC."** I am well aware of everything but can not digest fully **"how to use folder set child items and how to map them with ERPnext fields** and so on even you tried to explain your best

**Comment by pibico** [comment]
Let's try to do this as much as generic possible.

1.- We could create a new DocType, let's call it BookLet. It has several docfields, the knowledge area, the reference DocType (whichever doctype), once is set the doctype we can choose the DocName (whichever docname for the selected doctype) and we can add other fields.

![imagen](https://user-images.githubusercontent.com/69711454/166489801-2574bb55-03c2-4afd-8516-129ae20023ac.png)

2.- This DocType is really a Document Container, it means that we can attach as many files as we want (we can use the attachment item table and increase their columns if needed)

![imagen](https://user-images.githubusercontent.com/69711454/166490458-77ec27d1-0fd2-4e5d-a28b-b9f730181666.png)

3.- This way we can see the different booklets assign to a doctype (for example a Project) and list all documents in each booklet, and get thus, the list of documents of a patient, projects, categorized by booklets (knowledge-areas)

This generic approach could be valid to what you expect to have?

**Comment by pibico** [comment]
We have added the Booklet funcionality in Projects. Please use it and tell us, also in Projects it could be possible to create automatically Folders in NC in the same way as for Customer.

**Comment by chechani** [comment]
Thanks, It seems interesting, let us explore and understand it. On update, found error booklet items were not found. 

![booklet item](https://user-images.githubusercontent.com/6291292/166574315-a50012d9-8021-4dcd-bafa-a7e46256d408.jpg)

**Comment by chechani** [comment]
On Opening an existing project,  getting the following error

![opening project](https://user-images.githubusercontent.com/6291292/166576376-bc4fd70b-7853-41fa-beef-3c3e4063a4e8.jpg)



### App Versions
```
{
	"erpnext": "13.25.1",
	"erpnext_telegram_integration": "1.0.1",
	"frappe": "13.25.0",
	"frappe_system_monitor": "0.0.1",
	"pibicut": "0.0.1",
	"pibidav": "0.0.1",
	"professional": "0.0.1",
	"whitelabel": "0.0.1",
	"whitetheme_v13": "0.0.1"
}
```
### Route
```
Form/Project/Pilot Healthcare
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 68, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1213, in call
    return fn(*args, **newargs)
  File "apps/pibidav/pibidav/pibidav/custom.py", line 335, in get_nc_settings
    if use_default[0]['use_default_folder']:
IndexError: list index out of range

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doctype": "Project"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/pibidav.pibidav.custom.get_nc_settings"
}
```
### Response Data
```
{
	"exception": "IndexError: list index out of range"
}
```

**Comment by chechani** [comment]
On creation of a new project, getting the following error 

![new project](https://user-images.githubusercontent.com/6291292/166579043-19272a3f-6090-467d-b2b4-e5329dbed821.jpg)

### App Versions
```
{
	"erpnext": "13.25.1",
	"erpnext_telegram_integration": "1.0.1",
	"frappe": "13.25.0",
	"frappe_system_monitor": "0.0.1",
	"pibicut": "0.0.1",
	"pibidav": "0.0.1",
	"professional": "0.0.1",
	"whitelabel": "0.0.1",
	"whitetheme_v13": "0.0.1"
}
```
### Route
```
Form/Project/new-project-2
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 68, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1213, in call
    return fn(*args, **newargs)
  File "apps/pibidav/pibidav/pibidav/custom.py", line 335, in get_nc_settings
    if use_default[0]['use_default_folder']:
IndexError: list index out of range

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doctype": "Project"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/pibidav.pibidav.custom.get_nc_settings"
}
```
### Response Data
```
{
	"exception": "IndexError: list index out of range"
}
```

**Comment by chechani** [comment]
In Booklet creation, the Knowledge area field is linked to the department, is it right?

**Comment by pibico** [comment]
> Thanks, It seems interesting, let us explore and understand it. On update, found error booklet items were not found.
> 
> ![booklet item](https://user-images.githubusercontent.com/6291292/166574315-a50012d9-8021-4dcd-bafa-a7e46256d408.jpg)

Booklet Item DocType definition corrected and uncheck Custom Checkbox Checked.

**Comment by pibico** [comment]
> On Opening an existing project, getting the following error
> 
> ![opening project](https://user-images.githubusercontent.com/6291292/166576376-bc4fd70b-7853-41fa-beef-3c3e4063a4e8.jpg)
> ### App Versions
> 
> ```
> {
> 	"erpnext": "13.25.1",
> 	"erpnext_telegram_integration": "1.0.1",
> 	"frappe": "13.25.0",
> 	"frappe_system_monitor": "0.0.1",
> 	"pibicut": "0.0.1",
> 	"pibidav": "0.0.1",
> 	"professional": "0.0.1",
> 	"whitelabel": "0.0.1",
> 	"whitetheme_v13": "0.0.1"
> }
> ```
> 
> ### Route
> 
> ```
> Form/Project/Pilot Healthcare
> ```
> 
> ### Trackeback
> 
> ```
> Traceback (most recent call last):
>   File "apps/frappe/frappe/app.py", line 68, in application
>     response = frappe.api.handle()
>   File "apps/frappe/frappe/api.py", line 55, in handle
>     return frappe.handler.handle()
>   File "apps/frappe/frappe/handler.py", line 31, in handle
>     data = execute_cmd(cmd)
>   File "apps/frappe/frappe/handler.py", line 68, in execute_cmd
>     return frappe.call(method, **frappe.form_dict)
>   File "apps/frappe/frappe/__init__.py", line 1213, in call
>     return fn(*args, **newargs)
>   File "apps/pibidav/pibidav/pibidav/custom.py", line 335, in get_nc_settings
>     if use_default[0]['use_default_folder']:
> IndexError: list index out of range
> ```
> 
> ### Request Data
> 
> ```
> {
> 	"type": "POST",
> 	"args": {
> 		"doctype": "Project"
> 	},
> 	"headers": {},
> 	"error_handlers": {},
> 	"url": "/api/method/pibidav.pibidav.custom.get_nc_settings"
> }
> ```
> 
> ### Response Data
> 
> ```
> {
> 	"exception": "IndexError: list index out of range"
> }
> ```

The same way that Customer, on Project there must be included in DocTypes integrated in NextCloud Settings, and filled its NC related DocFields.

![imagen](https://user-images.githubusercontent.com/69711454/166633590-81d139cf-8dd5-4807-920e-1331b5cde355.png)

**Comment by pibico** [comment]
> On creation of a new project, getting the following error
> 
> ![new project](https://user-images.githubusercontent.com/6291292/166579043-19272a3f-6090-467d-b2b4-e5329dbed821.jpg)
> ### App Versions
> 
> ```
> {
> 	"erpnext": "13.25.1",
> 	"erpnext_telegram_integration": "1.0.1",
> 	"frappe": "13.25.0",
> 	"frappe_system_monitor": "0.0.1",
> 	"pibicut": "0.0.1",
> 	"pibidav": "0.0.1",
> 	"professional": "0.0.1",
> 	"whitelabel": "0.0.1",
> 	"whitetheme_v13": "0.0.1"
> }
> ```
> 
> ### Route
> 
> ```
> Form/Project/new-project-2
> ```
> 
> ### Trackeback
> 
> ```
> Traceback (most recent call last):
>   File "apps/frappe/frappe/app.py", line 68, in application
>     response = frappe.api.handle()
>   File "apps/frappe/frappe/api.py", line 55, in handle
>     return frappe.handler.handle()
>   File "apps/frappe/frappe/handler.py", line 31, in handle
>     data = execute_cmd(cmd)
>   File "apps/frappe/frappe/handler.py", line 68, in execute_cmd
>     return frappe.call(method, **frappe.form_dict)
>   File "apps/frappe/frappe/__init__.py", line 1213, in call
>     return fn(*args, **newargs)
>   File "apps/pibidav/pibidav/pibidav/custom.py", line 335, in get_nc_settings
>     if use_default[0]['use_default_folder']:
> IndexError: list index out of range
> ```
> 
> ### Request Data
> 
> ```
> {
> 	"type": "POST",
> 	"args": {
> 		"doctype": "Project"
> 	},
> 	"headers": {},
> 	"error_handlers": {},
> 	"url": "/api/method/pibidav.pibidav.custom.get_nc_settings"
> }
> ```
> 
> ### Response Data
> 
> ```
> {
> 	"exception": "IndexError: list index out of range"
> }
> ```

This is related with the last error, missing information or not included Project DocType in NextCloud Settings.

**Comment by chechani** [comment]
Thanks, The reported issue is gone but I could not achieve the functionality explained. I will invest more time to understand it and work in with a case example. Will Update you back.
