### ISSUE TITLE
Booklet Doctype to be set in Nexcloud Setting too ?

### ISSUE THREAD

**Issue by chechani** [pibico/pibiDAV#8]
We could not see the copy feature working, as we followed everything but we understand from the screenshot NC Setting dos not required for Booklet and for Attachment Items fields are already there and we might not require to add them IN NC setting. Also learnt that doc fields denied should be set mandatory otherwise thrown error. 

**Why Docs not uploaded to NC of Booklet Attachment Items, need to understand before further investigate**

Whether No client script is required for Booklet Items

![image](https://user-images.githubusercontent.com/6291292/166667418-e0181ce9-775a-42fd-8cb1-226e4f2dfd9a.png)

**Comment by pibico** [comment]
> We could not see the copy feature working, as we followed everything but we understand from the screenshot NC Setting dos not required for Booklet and for Attachment Items fields are already there and we might not require to add them IN NC setting. Also learnt that doc fields denied should be set mandatory otherwise thrown error.
> 
> **Why Docs not uploaded to NC of Booklet Attachment Items, need to understand before further investigate**
> 
> Whether No client script is required for Booklet Items
> 
> ![image](https://user-images.githubusercontent.com/6291292/166667418-e0181ce9-775a-42fd-8cb1-226e4f2dfd9a.png)

Really Booklet Doctype has nothing to do or little with NC Integration and we will remove it from pibiDAV.

So, we will make a new app called pibiBooklet for this new feature. Booklet Copy feature does not run on creation on a project.

Booklets are created before the assignment to a Project or whichever doctype you want to have booklets. So you create a Project and then you assign the booklets you want. That is how is being thought. For a core doctype to have booklets are needed the custom field Booklet Item defined as table multiselect link to Booklet Item, and the doctype link to that core doctype.

**Comment by chechani** [comment]
Ok, Noted !

**Comment by pibico** [comment]
booklet functionality has been migrated to app pibibooklet for further evolution outside pibiDAV. https://github.com/pibico/pibiBooklet/tree/master
